name: eighty_three_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # state management packages
  get:
  get_storage:
  # animation & lists (tools)
  flutter_screenutil: ^5.5.4
  # media
  cached_network_image: ^3.1.0+1
  # api packages
  dio_http_cache:
  dio:
  # debug log
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # clean code
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/mock_json/

  fonts:

    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica/Helvetica.ttf

    - family: CircularStd
      fonts:
        - asset: assets/fonts/circular_std_medium/CircularStd-Medium.otf

